### PR TITLE
merge binge and single, exit on completion

### LINKED ISSUE #22: Set to complete and ask for rating when finished
Small thing, but it would nice for the program to set the anime to completed (I think it already does this but it didn't do it all the time for me?) and ask for a rating instead of just quitting when you finish an anime/manga.

### LINKED ISSUE #29: Follow convention for yes/no questions
Shouldn't line 164 be switched out to be consistent with convention? I made yes default since it is capitalized instead of no. If you don't want yes to be default the n should be capitalized instead.

Example of how it could be fixed if yes is the default:
```
printf "No configuration file found. Would you like to generate a default one? [Y/n] " && read -r generate
case "$generate" in
"No" | "no" | "n" | "N") exit 0 ;;
```

### PR DESCRIPTION
**Pull request by VegardMatthey**
Still can't test for manga. Does manga not work or is it just me?
For the cases that are one line, should I join them like this?
 ```
"Watch Anime") binge "ANIME" ;;
```
Closes #22 
Closes #29

### CODE REVIEW

**Comment by justchokingaround** [comment]
> 

yes

**Comment by justchokingaround** [comment]
got manga to work again, i will test this PR more extensively in a few days

**Comment by VegardMatthey** [comment]
You are aware that the second commit makes total episodes in the anime_list off by one if it is currently releasing.

**Comment by justchokingaround** [comment]
no i'm not, thats a choke on my part :sob:, can u revert it pretty please?

**Comment by VegardMatthey** [comment]
It fixes more than it breaks tho.

**Comment by VegardMatthey** [comment]
Previously there was a question mark instead. And it is correct after you have selected episode using no anilist.

**Comment by justchokingaround** [comment]
oh

**Comment by VegardMatthey** [comment]
You can't really do math with regex so there is no simple fix.

**Comment by VegardMatthey** [comment]
The off by one is why I marked the commit OBO

**Comment by VegardMatthey** [comment]
The second commit was essentially trying to solve the issue that I referenced when asking for help on discord. The issue was later deleted for some reason.

**Comment by justchokingaround** [comment]
when a user watches an episode, then quits the player mid episode (before 85%, so before completing the whole episode), and presses yes to keep watching, it goes to the next episode even tho it should keep playing the same episode from the same position

**Comment by VegardMatthey** [comment]
Is there a way to see if the episode has been watched 85% or more?

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/jerry/blob/main/jerry.sh#L1066
that's what this variable is used for ^^^

example usage: https://github.com/justchokingaround/jerry/blob/main/jerry.sh#L986

**Comment by VegardMatthey** [comment]
Yes, I just found it.

**Comment by VegardMatthey** [comment]
What should it do if you quit early?

**Comment by justchokingaround** [comment]
not update progress to progress + 1

**Comment by justchokingaround** [comment]
also, the episodes releasing thing doesn't show up for the user list, it's only used when  a user looks up an anime:
Screenshot 2023-08-12 at 17 20 41


Screenshot 2023-08-12 at 17 21 10

if u don't have an anilist account, i can implement this later

**Comment by VegardMatthey** [comment]
Yes I did not update the get_anime_from_list function.

**Comment by VegardMatthey** [comment]
The episode numbers are fixed. Should I add (releasing) to the shows that are, or not?

**Comment by justchokingaround** [comment]
yes please, it looks nice

**Comment by VegardMatthey** [comment]
Should it be at the end or after the episode number?

**Comment by justchokingaround** [comment]
after ep number, in `()`

**Comment by VegardMatthey** [comment]
I added the (releasing) and if are dissatisfied with the placement just tell me. It is easy to change.

**Comment by justchokingaround** [comment]
yep, thx, ill check

**Comment by justchokingaround** [comment]
can you just add a space between `episodes` and `(releasing)` please? otherwise it looks great, its a good addition

**Comment by VegardMatthey** [comment]
changed.

**Comment by VegardMatthey** [comment]
Is there anything else?

**Comment by VegardMatthey** [comment]
Added fix for issue: #29 .

**Review by justchokingaround — APPROVED** [review]

**Pull request merged**
