### PR TITLE
Windows Image Preview + Bug Fixes

### PR DESCRIPTION
**Pull request by Corbett000**
This pull request needs additional testing in Linux to ensure that features involving preview of cover images still work. Especially when dealing with the external features. Manga should also be tested as I was having issues testing on Windows.

The main feature added is the ability to view media covers in the fzf preview window on Windows machines. The only currently known bug is the program stopping if up or down arrows are pressed while processing curl requests for image files, or if the sleep time (line 378) is not enough it might also stop.

Additional Features:

1. Option to select between sub or dub at runtime.
2. Option to include content marked as adult in search results.
3. Option to give additional arguments to chafa image preview
4. fzf prompt consistency

Bug Fixes

1. Provider variable was overwritten by providers in extract_from_json(). Modifying variable names provider->link_provider and providers->link_providers allowed binge() to function as expected when binging multiple episodes in a row.
2. If cover image files were not loaded into the temp directory, then the respective anime would not be listed by fzf.

Other Changes:

1. Temporary cover files are now titled by their media id instead of title/chapter/etc to prevent illegal characters and limit filename length.
2. update_progress() now directly takes the episode/chapter number to update to instead of adding 1 to the inputted episode/chapter number.
3. dub and chafa_method variables have been removed in place of sub_or_dub and chafa_options variables.

### CODE REVIEW

**Comment by justchokingaround** [comment]
is this ready for testing?

**Comment by justchokingaround** [comment]
looks very interesting, im excited for this

**Comment by Corbett000** [comment]
Yep. This is ready for additional testing. I am working on getting a virtual machine running to try and debug the external menu code as I am almost certain it is broken after changing some aspects of how the files work in Jerry. Additional testing without the external menu on Linux and/or mac would also be appreciated.

**Comment by justchokingaround** [comment]
ill do it tmr then, thx a lot for ur work

**Comment by justchokingaround** [comment]
the merge conflict fucked everything up lol. ill fix it

**Comment by justchokingaround** [comment]
tested all the stuff u mentioned and it works fine on linux. could you please re-review the changes i made (might have missed some stuff when dealing with merge conflicts) and check again if it works fine on windows. sorry for the trouble

**Comment by Corbett000** [comment]
It appears to still work fine on Windows. I think chafa_options should be mentioned on the wiki as the default value "-f sixel" will not work on Windows terminal as only the symbols format works properly. I found that omitting the -f option also works on Windows and just defaults to symbols format.

**Comment by justchokingaround** [comment]
oh yeah that was for testing, i put it on the wrong line

**Comment by justchokingaround** [comment]
should be fine now. can u do one last testing iteration pls? sorry for the trouble

**Comment by Corbett000** [comment]
Np. I just did a quick test on the chafa_options and it works fine. I believe it is ready to get merged.

Also it appears I forgot to mention that this PR includes my fix for searching for and reading manga if you want to give that a try. It works well as long as chapters are a whole number, but I believe I have a simple solution for that I can work on maybe Sunday.

**Comment by justchokingaround** [comment]
great! thanks a lot for the pr <3

**Pull request merged**
